export interface BlogYazisi {
  slug: string;
  baslik: string;
  baslikEn: string;
  ozet: string;
  ozetEn: string;
  tarih: string;
  okumaSuresi: number;
  etiketler: string[];
  icerik: BlogBolum[];
  ilgiliMizac?: string;
}

export interface BlogBolum {
  tip: 'h2' | 'h3' | 'p' | 'ul' | 'cta';
  metin?: string;
  metinEn?: string;
  maddeler?: string[];
  maddelerEn?: string[];
  href?: string;
  buton?: string;
  butonEn?: string;
}

export const blogYazilari: BlogYazisi[] = [
  {
    slug: 'mizac-testi-nedir',
    baslik: 'Mizaç Testi Nedir? İbn-i Sina\'nın 4 Mizaç Teorisi',
    baslikEn: 'What Is a Temperament Test? Ibn Sina\'s 4 Temperament Theory',
    ozet: 'İbn-i Sina\'nın geliştirdiği dört mizaç teorisi nedir, mizaç testi nasıl çalışır, hangi mizaç tipine giriyorsunuz? Bilimsel temelli kadim bilgeliği keşfedin.',
    ozetEn: 'What is Ibn Sina\'s four temperament theory, how does a temperament test work, and which type are you? Discover this scientifically-rooted ancient wisdom.',
    tarih: '2026-03-01',
    okumaSuresi: 6,
    etiketler: ['mizaç testi', 'ibn-i sina', '4 mizaç', 'mizaç nedir'],
    icerik: [
      { tip: 'p', metin: 'Mizaç, insanın doğuştan gelen ve hayatı boyunca değişmeyen temel karakter yapısını tanımlar. Hangi yiyeceklerden hoşlanırsınız, nasıl uyursunuz, stresle nasıl başa çıkarsınız — bunların tümü mizacınızla doğrudan ilişkilidir.' },
      { tip: 'p', metinEn: 'Temperament describes the fundamental character structure a person is born with and that does not change throughout life. Which foods you enjoy, how you sleep, how you cope with stress — all of these are directly related to your temperament.' },
      { tip: 'h2', metin: 'İbn-i Sina ve 4 Mizaç Teorisi' },
      { tip: 'p', metin: 'İbn-i Sina (980–1037), dünya tıp tarihinin en önemli isimlerinden biridir. Kaleme aldığı "El-Kanun fi\'t-Tıbb" (Tıbbın Kanunu) adlı eser, yüzyıllarca Avrupa ve İslam dünyasının temel tıp referansı olmuştur. Bu eserde İbn-i Sina, insanları dört temel mizaç tipine göre sınıflandırır: Safravî, Demevî, Balgamî ve Sevdavî.' },
      { tip: 'p', metin: 'Bu dört tip, dört temel element olan Ateş, Hava, Su ve Toprak ile ilişkilendirilir. Her elementin kendine özgü sıcaklık ve nem dengesi vardır; bu denge de insanın fiziksel, duygusal ve zihinsel yapısını belirler.' },
      { tip: 'h2', metin: '4 Mizaç Tipi Özet' },
      { tip: 'ul', maddeler: [
        'Safravî (Ateş): Enerjik, lider ruhlu, kararlı ve adalet duygusu güçlü. Sıcak ve kuru yapı.',
        'Demevî (Hava): Sosyal, neşeli, yaratıcı ve sevgi dolu. Sıcak ve nemli yapı.',
        'Balgamî (Su): Sakin, sabırlı, güvenilir ve temkinli. Soğuk ve nemli yapı.',
        'Sevdavî (Toprak): Derin düşünceli, yaratıcı, melankolik ve sadık. Soğuk ve kuru yapı.',
      ]},
      { tip: 'h2', metin: 'Mizaç Testi Nasıl Çalışır?' },
      { tip: 'p', metin: 'Modern mizaç testleri, İbn-i Sina\'nın teorisini temel alarak insanların fiziksel özelliklerini, duygusal tepkilerini, uyku düzenlerini, beslenme alışkanlıklarını ve sosyal davranışlarını ölçer. 50 soruluk kapsamlı testimiz bu dört alanı dengeli biçimde ele alır.' },
      { tip: 'h2', metin: 'Mizaç Bilmek Neden Önemlidir?' },
      { tip: 'ul', maddeler: [
        'Sağlık: Hangi hastalıklara yatkınsınız, hangi besinler size iyi gelir?',
        'İlişkiler: Hangi mizaçlarla uyumlusunuz, çatışmayı nasıl yönetirsiniz?',
        'Kariyer: Hangi meslekler ve ortamlar size en uygun?',
        'Kişisel gelişim: Hangi alanlarda güçlü, hangi alanlarda gelişime açıksınız?',
      ]},
      { tip: 'cta', metin: '50 soruluk ücretsiz mizaç testini şimdi yap', buton: 'Testi Başlat', href: '/test' },
    ],
  },
  {
    slug: 'safravi-mizac-nedir',
    baslik: 'Safravî Mizaç Nedir? Özellikleri, Güçlü Yönleri ve Sağlık İpuçları',
    baslikEn: 'What Is Choleric Temperament? Traits, Strengths & Health Tips',
    ozet: 'Safravî mizaç; ateş elementi, güçlü liderlik ve kararlılıkla tanımlanan bir karakter yapısıdır. Özellikleri, sağlık tavsiyeleri ve uyumlu mizaçları keşfedin.',
    ozetEn: 'Choleric temperament is defined by the fire element, strong leadership and decisiveness. Discover its traits, health advice and compatible temperaments.',
    tarih: '2026-03-05',
    okumaSuresi: 7,
    etiketler: ['safravi mizac', 'ateş mizacı', 'koleri mizaç', 'safra mizacı özellikleri'],
    ilgiliMizac: 'safravi',
    icerik: [
      { tip: 'p', metin: 'Safravî mizaç, İbn-i Sina\'nın dört mizaç sınıflandırmasının en ateşli ve dinamik olanıdır. Ateş elementi ile ilişkilendirilen bu mizaç tipi; sıcak ve kuru yapısıyla öne çıkar. Safravî insanlar doğal liderler, kararlı karar alıcılar ve güçlü adalet duygusuyla tanınan bireylerdir.' },
      { tip: 'h2', metin: 'Safravî Mizacın Temel Özellikleri' },
      { tip: 'ul', maddeler: [
        'Enerji ve dinamizm: Sabahları erken kalkar, güne hızlı başlar',
        'Liderlik: Doğal otorite, insan yönetme becerisi',
        'Kararlılık: Hızlı karar verir, kararsızlıktan hoşlanmaz',
        'Adalet duygusu: Haksızlığa tahammülü yoktur',
        'Dobralık: Düşündüğünü açıkça söyler, dolaylı anlatımdan kaçınır',
        'Görsellik: Estetiğe önem verir, çevresini düzenli tutar',
        'Rekabet: Kazanmayı ve başarıyı sever',
      ]},
      { tip: 'h2', metin: 'Safravî Fiziksel Özellikleri' },
      { tip: 'p', metin: 'Safravî mizaçlı kişiler genellikle ince-orta yapılı, çabuk hareket eden ve enerjik görünen bireylerdir. Derisi ve saçı çoğunlukla kuru olma eğilimindedir. Vücut ısısı yüksektir; sıcak havalara ve ortamlara karşı hassasiyetleri olabilir. Uyku süreleri diğer mizaçlara göre daha kısadır.' },
      { tip: 'h2', metin: 'Safravî Mizacında Sağlık ve Hastalıklar' },
      { tip: 'p', metin: 'Ateş elementi nedeniyle Safravî mizaçlılar, iltihaplı durumlar ve sindirim sorunlarına yatkındır. Migren, karaciğer sorunları, cilt problemleri ve aşırı sinirlilik bu mizacın dikkat etmesi gereken alanlardır.' },
      { tip: 'ul', maddeler: [
        'Soğutucu besinler tüketin: Salatalık, yoğurt, nane',
        'Kızartma ve baharatlı yiyeceklerden kaçının',
        'Düzenli, hafif egzersiz yapın; aşırı yoğunlaşmaktan kaçının',
        'Yeterli uyku düzeni oluşturun',
        'Öfke ve stresi yönetmek için meditasyon veya nefes egzersizleri yapın',
      ]},
      { tip: 'h2', metin: 'Safravî\'nin Kariyer ve İş Hayatı' },
      { tip: 'p', metin: 'Liderlik ruhu ve kararlılığı sayesinde Safravîler yöneticilik, girişimcilik, hukuk, askerlik ve tıp gibi alanlarda öne çıkar. Takım yönetimi ve proje liderliği bu mizacın en iyi performans gösterdiği alanlardır.' },
      { tip: 'h2', metin: 'Safravî Mizacı ile Uyumlu Mizaçlar' },
      { tip: 'p', metin: 'Safravî ile en yüksek uyumu Balgamî mizaç gösterir (%92). Safravî\'nin ateşli yapısını Balgamî\'nin sakinliği dengeler. Demevî ile de iyi anlaşılır (%68). En zorlu uyum Sevdavî ile yaşanır.' },
      { tip: 'cta', metin: 'Safravî mizacın mısın? Testi yap ve öğren', buton: 'Ücretsiz Testi Başlat', href: '/test' },
    ],
  },
  {
    slug: 'demevi-mizac-nedir',
    baslik: 'Demevî Mizaç Nedir? Neşeli, Sosyal ve Yaratıcı Ruh',
    baslikEn: 'What Is Sanguine Temperament? Joyful, Social and Creative Spirit',
    ozet: 'Demevî mizaç; hava elementi, sosyallik, neşe ve yaratıcılıkla öne çıkan bir karakter yapısıdır. İbn-i Sina geleneğinde "aşk insanı" olarak tanımlanan bu mizacı keşfedin.',
    ozetEn: 'Sanguine temperament stands out for its air element, sociability, joy and creativity. Discover this temperament, described as the "person of love" in Ibn Sina\'s tradition.',
    tarih: '2026-03-08',
    okumaSuresi: 7,
    etiketler: ['demevi mizac', 'hava mizacı', 'sanguine mizaç', 'kan mizacı'],
    ilgiliMizac: 'demevi',
    icerik: [
      { tip: 'p', metin: 'Demevî mizaç, dört mizaç tipinin en neşeli ve sosyal olanıdır. Hava elementi ile ilişkilendirilen bu yapı; sıcak ve nemli karakteriyle hem fiziksel hem duygusal canlılığı temsil eder. İbn-i Sina geleneğinde Demevî, "aşk insanı" olarak tanımlanır.' },
      { tip: 'h2', metin: 'Demevî Mizacın Temel Özellikleri' },
      { tip: 'ul', maddeler: [
        'Sosyallik: İnsan içinde olmayı sever, kolay arkadaşlık kurar',
        'Neşe ve coşku: Hayata pozitif bakar, şenlik atmosferi yaratır',
        'Yaratıcılık: Sanat, müzik, yazı ve tasarımda yetenekli',
        'Cömertlik: Vermeyi ve paylaşmayı sever',
        'Maneviyat: Ruhsal konulara ilgisi yüksektir',
        'Çok uyku ihtiyacı: Diğer mizaçlara göre daha fazla uyur',
        'Anlık yaşama eğilimi: Planlamadan ziyade anda olmayı tercih eder',
      ]},
      { tip: 'h2', metin: 'Demevî Fiziksel Özellikleri' },
      { tip: 'p', metin: 'Demevî mizaçlılar genellikle yumuşak hatları olan, dolgun ya da orta yapılı, uysal görünümlü bireylerdir. Cildi ve saçı çoğunlukla yumuşak ve nemlidir. Uyuma eğilimleri güçlüdür; yeterli uyku almadıklarında performansları belirgin biçimde düşer.' },
      { tip: 'h2', metin: 'Demevî Mizacında Sağlık ve Hastalıklar' },
      { tip: 'p', metin: 'Nemli yapısı nedeniyle Demevî mizaçlılar üst solunum yolu hastalıklarına, aşırı kilo almaya ve balgam birikimine yatkındır. Şeker dengesi ve solunum sağlığı dikkat gerektiren alanlardır.' },
      { tip: 'ul', maddeler: [
        'Kurutucu özellikte besinler tercih edin: Arpa, nane, zencefil çayı',
        'Aşırı tatlı ve un mamullerinden kaçının',
        'Düzenli hareket ve açık hava aktiviteleri şarttır',
        'Sabah güneşine çıkmak enerji verir',
        'Aşırı uyku yerine kaliteli uyku odaklanın',
      ]},
      { tip: 'h2', metin: 'Demevî\'nin Kariyer ve İş Hayatı' },
      { tip: 'p', metin: 'Demevî mizaçlılar; sanat, müzik, eğitim, sosyal hizmetler, iletişim ve insan ilişkileri gerektiren alanlarda parlar. İnsanlarla çalışmayı ve yaratıcı ortamları severler.' },
      { tip: 'h2', metin: 'Demevî Mizacı ile Uyumlu Mizaçlar' },
      { tip: 'p', metin: 'Demevî ile en yüksek uyumu Sevdavî mizaç gösterir (%90). Bu iki mizaç birbirini hem duygusal hem entelektüel düzeyde tamamlar. Safravî ile de iyi anlaşılır (%72).' },
      { tip: 'cta', metin: 'Demevî mizacın mısın? Testi yap ve öğren', buton: 'Ücretsiz Testi Başlat', href: '/test' },
    ],
  },
  {
    slug: 'balgami-mizac-nedir',
    baslik: 'Balgamî Mizaç Nedir? Sakin, Sabırlı ve Güvenilir Karakter',
    baslikEn: 'What Is Phlegmatic Temperament? Calm, Patient and Reliable Character',
    ozet: 'Balgamî mizaç; su elementi, sabır, güvenilirlik ve derin bağlılıkla tanımlanan bir yapıdır. Bu sakin ve temkinli mizacın sağlık, kariyer ve ilişki özelliklerini keşfedin.',
    ozetEn: 'Phlegmatic temperament is defined by the water element, patience, reliability and deep loyalty. Discover the health, career and relationship traits of this calm temperament.',
    tarih: '2026-03-10',
    okumaSuresi: 7,
    etiketler: ['balgami mizac', 'su mizacı', 'phlegmatic mizaç', 'balgam mizacı özellikleri'],
    ilgiliMizac: 'balgami',
    icerik: [
      { tip: 'p', metin: 'Balgamî mizaç, dört mizaç tipinin en sakin ve temkinli olanıdır. Su elementi ile ilişkilendirilen bu yapı; soğuk ve nemli karakteriyle derin bir istikrarı temsil eder. Balgamî insanlar; güvenilirliği, sadakati ve sabırlarıyla çevrelerinde huzur yaratırlar.' },
      { tip: 'h2', metin: 'Balgamî Mizacın Temel Özellikleri' },
      { tip: 'ul', maddeler: [
        'Sakinlik: Sükûneti korur, paniklemez',
        'Sabır: Uzun vadeli hedeflere odaklanabilir',
        'Güvenilirlik: Verdiği sözü tutar, sorumluluk sahibidir',
        'Derin bağlılık: Bağlandığı kişilere ömür boyu sadık kalır',
        'Temkinlilik: Karar vermeden önce iyice düşünür',
        'Kırgınlıklarını içine atma: Üzüntüsünü dışarı vurmakta güçlük çeker',
        'Huzur yaratma: Bulunduğu ortamı sakinleştirir',
      ]},
      { tip: 'h2', metin: 'Balgamî Fiziksel Özellikleri' },
      { tip: 'p', metin: 'Balgamî mizaçlılar genellikle dolgun ya da tombul yapılı, yavaş ve ölçülü hareket eden bireylerdir. Metabolizmaları diğer mizaçlara göre daha yavaş çalışır. Soğuğa karşı hassasiyetleri yüksektir; donuk hava ve serin ortamlar onları zorlayabilir.' },
      { tip: 'h2', metin: 'Balgamî Mizacında Sağlık ve Hastalıklar' },
      { tip: 'p', metin: 'Soğuk ve nemli yapısı nedeniyle Balgamî mizaçlılar üst solunum yolu rahatsızlıklarına, eklem ağrılarına, balgam birikimine ve kilo problemlerine yatkındır. Tiroit yavaşlığı ve sindirim tembelliği de dikkat edilmesi gereken alanlardır.' },
      { tip: 'ul', maddeler: [
        'Isıtıcı ve uyarıcı besinler tüketin: Zencefil, tarçın, karanfil',
        'Soğuk ve hamur işlerinden kaçının',
        'Düzenli ve tempolu egzersiz yapın',
        'Sabah yürüyüşleri metabolizmayı hızlandırır',
        'Kırgınlıkları dışa vurmayı öğrenin; duygusal birikim sağlığı etkiler',
      ]},
      { tip: 'h2', metin: 'Balgamî\'nin Kariyer ve İş Hayatı' },
      { tip: 'p', metin: 'Balgamî mizaçlılar; psikoloji, rehberlik, hemşirelik, araştırma, muhasebe ve uzun vadeli planlama gerektiren alanlarda başarılıdır. Güvenilir ekip oyuncularıdır ve liderden çok uzlaştırıcı rolünü benimserler.' },
      { tip: 'h2', metin: 'Balgamî Mizacı ile Uyumlu Mizaçlar' },
      { tip: 'p', metin: 'Balgamî ile en yüksek uyumu Safravî mizaç gösterir (%92). Balgamî\'nin sakinliği Safravî\'nin dinamizmini dengeler; bu zıt çekim ilişkisi çok güçlü bağlar oluşturabilir. Sevdavî ile de derin bir uyum yaşanır (%76).' },
      { tip: 'cta', metin: 'Balgamî mizacın mısın? Testi yap ve öğren', buton: 'Ücretsiz Testi Başlat', href: '/test' },
    ],
  },
  {
    slug: 'sevdavi-mizac-nedir',
    baslik: 'Sevdavî Mizaç Nedir? Derin, Yaratıcı ve Melankolik Yapı',
    baslikEn: 'What Is Melancholic Temperament? Deep, Creative and Melancholic Structure',
    ozet: 'Sevdavî mizaç; toprak elementi, derin düşünce, yaratıcılık ve melankoliyle öne çıkan bir karakter yapısıdır. Bu derin ve karmaşık mizacı İbn-i Sina\'nın gözünden keşfedin.',
    ozetEn: 'Melancholic temperament stands out for its earth element, deep thinking, creativity and melancholy. Discover this deep and complex temperament through Ibn Sina\'s perspective.',
    tarih: '2026-03-12',
    okumaSuresi: 7,
    etiketler: ['sevdavi mizac', 'toprak mizacı', 'melankolik mizaç', 'sevda mizacı özellikleri'],
    ilgiliMizac: 'sevdavi',
    icerik: [
      { tip: 'p', metin: 'Sevdavî mizaç, dört mizaç tipinin en derin ve karmaşık olanıdır. Toprak elementi ile ilişkilendirilen bu yapı; soğuk ve kuru karakteriyle güçlü bir içsel dünyayı temsil eder. Sevdavîler; felsefi derinliği, sanatsal yaratıcılığı ve yoğun sadakatleriyle ayrışır.' },
      { tip: 'h2', metin: 'Sevdavî Mizacın Temel Özellikleri' },
      { tip: 'ul', maddeler: [
        'Derin düşünce: Her şeyi detaylıca analiz eder, sığ konuşmalardan hoşlanmaz',
        'Sanatsal yaratıcılık: Müzik, şiir, yazı ve sanata güçlü ilgi',
        'Sadakat: Bağlandığı kişilere ömür boyu bağlı kalır',
        'Mükemmeliyetçilik: İşini en iyi şekilde yapmak ister',
        'Hassasiyet: Eleştiriye ve reddedilmeye karşı hassastır',
        'Melankoli: Geçmişi düşünmeye, derinlemesine hissetmeye yatkındır',
        'Az konuşma: Sözü ölçer, gereksiz konuşmaktan kaçınır',
      ]},
      { tip: 'h2', metin: 'Sevdavî Fiziksel Özellikleri' },
      { tip: 'p', metin: 'Sevdavî mizaçlılar genellikle ince yapılı, soluk tenli ve içe dönük görünümlü bireylerdir. Uyku düzenleri düzensiz olabilir; uykuya dalmakta güçlük çekebilirler. Soğuk ve kuru havalarda daha fazla etkilenirler.' },
      { tip: 'h2', metin: 'Sevdavî Mizacında Sağlık ve Hastalıklar' },
      { tip: 'p', metin: 'Soğuk ve kuru yapısı nedeniyle Sevdavîler eklem ve kemik sorunlarına, sinir sistemi hassasiyetine, depresyon eğilimine ve uyku bozukluklarına yatkındır. Kaygı ve obsesif düşünceler de bu mizacın dikkat etmesi gereken alanlardır.' },
      { tip: 'ul', maddeler: [
        'Islatıcı ve ısıtıcı besinler tüketin: İncir, bal, zeytinyağı, çorba',
        'Kuru ve soğuk besinlerden kaçının',
        'Düzenli, hafif tempolu yürüyüşler ruhu dengeleyir',
        'Güneş ışığına maruz kalmak depresif dönemlerde yardımcı olur',
        'Yaratıcı bir uğraş edinin: Müzik, yazı veya resim ruhsal denge sağlar',
      ]},
      { tip: 'h2', metin: 'Sevdavî\'nin Kariyer ve İş Hayatı' },
      { tip: 'p', metin: 'Sevdavî mizaçlılar; felsefe, yazarlık, araştırma, mühendislik, arkeoloji ve sanat alanlarında olağanüstü başarı gösterir. Yoğun sosyal ortamlardan çok, bağımsız çalışabildikleri ve derine inebilecekleri alanlara yönelmelidirler.' },
      { tip: 'h2', metin: 'Sevdavî Mizacı ile Uyumlu Mizaçlar' },
      { tip: 'p', metin: 'Sevdavî ile en yüksek uyumu Demevî mizaç gösterir (%90). Demevî\'nin neşesi ve sosyalliği, Sevdavî\'nin içsel dünyasını dengeleyip aydınlatır. Balgamî ile de derin ve huzurlu bir uyum yaşanır (%74).' },
      { tip: 'cta', metin: 'Sevdavî mizacın mısın? Testi yap ve öğren', buton: 'Ücretsiz Testi Başlat', href: '/test' },
    ],
  },
  {
    slug: 'dort-halife-mizaci',
    baslik: 'Dört Halifenin Mizacı: Hz. Ebubekir, Ömer, Osman ve Ali',
    baslikEn: 'The Four Caliphs and Their Temperaments: Abu Bakr, Umar, Uthman and Ali',
    ozet: 'İslam tarihinin dört büyük halifesi İbn-i Sina\'nın mizaç teorisiyle inceleniyor. Ebubekir\'in Demevî, Ömer\'in Safravî, Osman\'ın Balgamî, Ali\'nin Sovdavî mizacı nasıl şekillendi?',
    ozetEn: 'The four great caliphs of Islamic history analyzed through Ibn Sina\'s temperament theory. How did Abu Bakr\'s Sanguine, Umar\'s Choleric, Uthman\'s Phlegmatic and Ali\'s Melancholic temperament shape history?',
    tarih: '2026-03-20',
    okumaSuresi: 8,
    etiketler: ['dört halife mizacı', 'hz ömer mizacı', 'hz ali mizacı', 'sahabe mizaç', 'ebubekir demevi'],
    icerik: [
      { tip: 'p', metin: 'İslam tarihinin dört büyük halifesi — Hz. Ebubekir, Hz. Ömer, Hz. Osman ve Hz. Ali — yalnızca siyasi lider değil, birer mizaç şahididir. İbn-i Sina geleneğine göre her insan dört elementten birinin ağırlığını taşır. Bu dört halife de sanki her bir mizacı temsil etmek üzere seçilmiş gibidir.' },
      { tip: 'h2', metin: 'Hz. Ebubekir — Demevî Mizaç (Hava Elementi)' },
      { tip: 'p', metin: 'Hz. Ebubekir, İslam\'ın ilk halifesi olarak bilinir. Onun en belirgin özelliği, insanlara karşı beslediği derin sevgi ve cömertliğidir. Mal varlığının tamamını Allah yolunda harcamış, azat ettiği köleler ve beslediği yoksullarla tarihte iz bırakmıştır. Bu sıcak kalplilik, yaratıcılık ve geniş gönüllülük, Demevî mizacın en belirgin işaretleridir.' },
      { tip: 'h2', metin: 'Hz. Ömer — Safravî Mizaç (Ateş Elementi)' },
      { tip: 'p', metin: 'Hz. Ömer, kararlılığı ve adaleti ile tanınan bir liderdir. Müslüman olmadan önce güçlü bir muhalif, Müslüman olduktan sonra ise İslam\'ın en güçlü savunucularından biri oldu. Safravî mizacın tipik özelliği olan bu keskin dönüşüm kapasitesi, onu tarihte eşsiz kılar. Devlet yönetimindeki sistematik yapısı, hızlı ve etkili kararları — bunların tamamı ateşin yakıcı netliğini yansıtır.' },
      { tip: 'h2', metin: 'Hz. Osman — Balgamî Mizaç (Su Elementi)' },
      { tip: 'p', metin: 'Hz. Osman, sakinliği ve cömertliği ile bilinir. İki hicretin adamı olarak tarihte yer alır — hem Habeşistan\'a hem de Medine\'ye hicret etmiştir. Kur\'an\'ın çoğaltılması ve dağıtılması onun döneminde gerçekleşmiştir. Balgamî mizacın sabır, huzur yayma ve derin adanmışlık özellikleri Osman\'ın hayatında net biçimde görülür.' },
      { tip: 'h2', metin: 'Hz. Ali — Sovdavî Mizaç (Toprak Elementi)' },
      { tip: 'p', metin: 'Hz. Ali, İslam\'ın en derin ilim ve hikmet sahibi isimlerinden biridir. Şiirsel ifadesi, felsefi derinliği ve adalet anlayışı onu diğerlerinden ayırır. "İlmin kapısı" olarak anılan Hz. Ali, Sovdavî mizacın en güçlü temsilcilerinden biridir. Melankolik derinlik, derin sadakat ve entelektüel yaratıcılık bu mizacın mühürleridir.' },
      { tip: 'cta', metin: 'Dört halifenin mizaç analizini detaylı incele', buton: 'Dört Halife Sayfasına Git', href: '/dort-halife' },
    ],
  },
  {
    slug: 'mizaca-gore-hastaliklar',
    baslik: 'Mizaca Göre Hastalıklar: Bedeninizin Hangi Sinyali Verdiğini Anlayın',
    baslikEn: 'Illness by Temperament: Understanding Your Body\'s Signals',
    ozet: 'Safravî yanma, Demevî zonklama, Balgamî tutulma, Sovdavî sızı — İbn-i Sina\'ya göre ağrının şekli mizacı ele verir. Her mizacın yatkın hastalıkları ve ruhsal kökleri.',
    ozetEn: 'Choleric burning, Sanguine throbbing, Phlegmatic stiffness, Melancholic aching — according to Ibn Sina, the type of pain reveals the temperament. Prone illnesses and emotional roots.',
    tarih: '2026-03-22',
    okumaSuresi: 7,
    etiketler: ['mizaç hastalık', 'safravi hastalıkları', 'balgami hastalıkları', 'mizaç ağrı tipi', 'duygu hastalık'],
    icerik: [
      { tip: 'p', metin: 'İbn-i Sina\'ya göre beden, ruhun aynasıdır. Hangi mizacı taşıyorsanız, hastalıklar da o mizacın zayıf noktalarından çıkmaya meyillidir. Dahası, ağrının şekli bile mizacı ele verir: yanıyorsanız Safravî, zonkluyorsanız Demevî, tutuluyorsanız Balgamî, sızıyorsanız Sovdavî sinyali alıyor olabilirsiniz.' },
      { tip: 'h2', metin: 'Ağrı Tipleri ve Mizaç İlişkisi' },
      { tip: 'ul', maddeler: [
        'Safravî: Yanma hissi — mide, safra kesesi, cilt',
        'Demevî: Zonklama — baş ağrısı, migren, kalp çarpıntısı',
        'Balgamî: Tutulma — eklemler, nefes yolları, sinüsler',
        'Sovdavî: Sızı — kemikler, sinirler, kronik ağrılar',
      ]},
      { tip: 'h2', metin: 'Duygular ve Hastalık: Görünmez Bağlantı' },
      { tip: 'p', metin: 'İbn-i Sina geleneğinde her hastalığın bir ruhsal kökü vardır. Aşırı öfke safra hıltını artırır ve mide ile safra kesesini yorar. Kronik keder, balgam hıltını artırarak akciğerleri etkiler. Aşırı sevinç ve heyecan kan hıltını yükseltir; kalp ve karaciğer etkilenir. Vesvese ve derin hüzün ise sevda hıltını artırarak sinir ve kemik sistemini yorar.' },
      { tip: 'h2', metin: 'Neden Hastalık Tekrarlanır?' },
      { tip: 'p', metin: 'Aynı hastalığın defalarca geri dönmesinin sebebi, genellikle mizacın dikkate alınmamasıdır. Balgamî bir kişi, sinüziti ilaçla bastırdıktan sonra tekrar aynı sorunla karşılaşırsa; bu, bedenin hâlâ ıslak ve soğuk bir ortamda olduğunu söylemesidir. Kök, mizaçta yatar.' },
      { tip: 'cta', metin: 'Mizacına göre hastalık ve şifa rehberini incele', buton: 'Hastalıklar Sayfasına Git', href: '/hastaliklar' },
    ],
  },
  {
    slug: 'alti-cesit-gida',
    baslik: 'Altı Çeşit Gıda: Yemekten Fazlası ile Beslenin',
    baslikEn: 'Six Types of Nourishment: Feed Yourself Beyond Food',
    ozet: 'İbn-i Sina\'ya göre gıda sadece tabağınızdaki değildir. Gördüğünüz, duyduğunuz, kokladığınız, hissettiğiniz her şey — bedeninizi ve ruhunuzu besler ya da yorar.',
    ozetEn: 'According to Ibn Sina, food is not only what is on your plate. Everything you see, hear, smell and feel — nourishes or exhausts your body and soul.',
    tarih: '2026-03-24',
    okumaSuresi: 6,
    etiketler: ['altı çeşit gıda', 'gıda kavramı', 'duygusal gıda', 'görsel gıda', 'ibn sina beslenme'],
    icerik: [
      { tip: 'p', metin: '"Gıda, insan bedenine ve ruhuna, dışardan içeriye aldığı andan itibaren etki ve iz bırakan her şeydir." Bu tanım, modern beslenme anlayışını kökünden sarsar. İbn-i Sina\'ya göre sadece yedikleriniz değil, baktıklarınız, dinledikleriniz, dokunduklarınız ve hissettikleriniz de birer gıdadır.' },
      { tip: 'h2', metin: '6 Çeşit Gıda' },
      { tip: 'ul', maddeler: [
        '1. Görsel Gıdalar: Yeşile bakmak, ufka bakmak, güzellikleri seyretmek',
        '2. İşitsel Gıdalar: Enstrümantal müzik, doğa sesleri, güzel söz',
        '3. Kokusal Gıdalar: Lavanta, gül, nane, günlük — her koku bir etki',
        '4. Tensel Gıdalar: Güneş ışığı, toprağa çıplak basmak, sevgi dolu dokunuş',
        '5. Duygusal Gıdalar: Sevilmek, takdir görmek, minnet etmek',
        '6. Ağız Yoluyla Alınan Gıdalar: Yedikleriniz, içtikleriniz, tatlar',
      ]},
      { tip: 'h2', metin: 'Duygusal Gıdanın Gücü' },
      { tip: 'p', metin: 'İbn-i Sina geleneğine göre duygusal gıdalar en hızlı ve en kalıcı etkiyi bırakanıdır. İlgi görmemek ve sevilmemek kilo artışına yol açabilir. Kıskançlık kaşıntıyı tetikler. Ayrılık acısı egzama olarak beden yüzeyine çıkar. Öte yandan sevilmek, takdir görmek ve minnet etmek — bunlar en derin besleyici duygusal gıdalardır.' },
      { tip: 'h2', metin: 'Müslih: Zıttıyla Dengele' },
      { tip: 'p', metin: 'İbn-i Sina, her gıdanın bir müslihi (dengeleyicisi) olduğunu öğretir. Kuru hurma yerseniz tereyağı ile dengeleyin. Kuzu eti yiyince salatalık ekleyin. Yoğurda kuru nane katın. Bu kadim denge prensibi, bedenin mizacını korur.' },
      { tip: 'cta', metin: 'Gıda kavramını derinlemesine keşfet', buton: 'Gıda Kavramı Sayfasına Git', href: '/gida-kavrami' },
    ],
  },
  {
    slug: 'mizaca-gore-nefes',
    baslik: 'Mizacına Göre Nefes Al: Her Mizacın Nefes Tekniği',
    baslikEn: 'Breathe According to Your Temperament: Breathing Techniques for Each Type',
    ozet: 'Yanlış nefes tekniği dengesizliği artırabilir. Safravî için soğutucu, Balgamî için ısıtıcı, Demevî için dengeleyici, Sovdavî için topraklayıcı nefes teknikleri.',
    ozetEn: 'The wrong breathing technique can increase imbalance. Cooling for Choleric, warming for Phlegmatic, balancing for Sanguine, grounding for Melancholic breathing techniques.',
    tarih: '2026-03-26',
    okumaSuresi: 5,
    etiketler: ['mizaç nefes', 'nefes egzersizi mizaç', 'safravi nefes', 'balgami nefes', 'nefes şifa'],
    icerik: [
      { tip: 'p', metin: 'İbn-i Sina\'ya göre nefes, bedenin en hızlı düzenleyicisidir. Birkaç dakikada kan basıncını düşürebilir, öfkeyi yatıştırabilir, enerji verebilir veya uykuyu getirebilir. Ancak doğru teknik, mizaca göre değişir.' },
      { tip: 'h2', metin: 'Safravî — Soğutucu Nefes' },
      { tip: 'p', metin: 'Ateş elementi olan Safravî mizaç için nefes; içteki yangını söndürmek amacıyla kullanılır. Sitali (soğutucu nefes) ve diyaframik derin nefes bu mizaç için idealdir. Mide yanması ve öfke anlarında 4-8 saniyelik derin nefes yalnızca dakikalar içinde fark yaratır.' },
      { tip: 'h2', metin: 'Demevî — Dengeleyici Nefes' },
      { tip: 'p', metin: 'Hava elementi olan Demevî için nefes; coşkuyu ve kan dolaşımını dengelemek içindir. Box Breathing (4-4-4-4) ve Alternate Nostril tekniği, kalp ve karaciğer üzerindeki stresi azaltır.' },
      { tip: 'h2', metin: 'Balgamî — Isıtıcı & Canlandırıcı Nefes' },
      { tip: 'p', metin: 'Su elementi olan Balgamî için nefes; soğuk ve ıslak bedeni ısıtmak ve akciğerleri temizlemek içindir. Kapalabhati (ateş nefesi) sabah yapıldığında metabolizmayı harekete geçirir, balgam birikimini çözer.' },
      { tip: 'h2', metin: 'Sovdavî — Topraklayıcı Nefes' },
      { tip: 'p', metin: 'Toprak elementi olan Sovdavî için nefes; sinir sistemini sakinleştirmek ve kronik ağrıyı azaltmak içindir. 4-7-8 tekniği ve Topraklama Nefesi, özellikle gece yapıldığında uyku kalitesini çarpıcı biçimde iyileştirir.' },
      { tip: 'cta', metin: 'Mizacına göre nefes tekniklerini keşfet', buton: 'Nefes Sayfasına Git', href: '/nefes' },
    ],
  },
  {
    slug: 'mizac-uyumu-iliskiler',
    baslik: 'Mizaç Uyumu: Hangi Mizaçlar Birbirine Uyumlu?',
    baslikEn: 'Temperament Compatibility: Which Temperaments Match?',
    ozet: 'Safravî, Demevî, Balgamî ve Sevdavî mizaçları arasındaki uyum ilişkileri. Aşk, arkadaşlık ve iş hayatında hangi mizaçlar birbirini tamamlar?',
    ozetEn: 'Compatibility between Choleric, Sanguine, Phlegmatic and Melancholic temperaments. Which temperaments complement each other in love, friendship and work life?',
    tarih: '2026-03-15',
    okumaSuresi: 5,
    etiketler: ['mizaç uyumu', 'mizaç ilişki', 'hangi mizaçlar uyumlu', 'mizaç çiftleri'],
    icerik: [
      { tip: 'p', metin: 'İbn-i Sina\'nın mizaç teorisine göre, zıt elementler birbirini dengeler ve çeker. Bu prensibi ilişkilere uyguladığımızda ortaya ilginç uyum haritaları çıkar.' },
      { tip: 'h2', metin: 'Neden Zıt Mizaçlar Çekilir?' },
      { tip: 'p', metin: 'Doğada ateş ve su, hava ve toprak birbirini dengeler. Aynı şekilde Safravî (Ateş) ve Balgamî (Su) birbirini tamamlar. Bu zıtlık ilk başta çatışma gibi görünse de uzun vadede derin bir denge ve bütünleşme sağlar.' },
      { tip: 'h2', metin: 'En Uyumlu Mizaç Çiftleri' },
      { tip: 'ul', maddeler: [
        'Safravî + Balgamî (%92): En güçlü zıt çekim. Ateş ve su dengesi.',
        'Demevî + Sevdavî (%90): Neşe ve derinlik mükemmel tamamlanır.',
        'Balgamî + Sevdavî (%76): İki soğuk element, derin ve huzurlu birliktelik.',
        'Safravî + Demevî (%72): Dinamizm ve sosyallik birbirini besler.',
      ]},
      { tip: 'h2', metin: 'İş Hayatında Mizaç Uyumu' },
      { tip: 'p', metin: 'İş ortamında uyum, aşk ilişkisinden farklıdır. Birbirini tamamlayan mizaçlar daha verimli ekipler oluşturur. Safravî lider olurken Balgamî uygulayıcı rol üstlenir; Demevî ilişkileri güçlendirir, Sevdavî ise analitik derinlik katar.' },
      { tip: 'h2', metin: 'Zorlu Mizaç Kombinasyonları' },
      { tip: 'p', metin: 'Aynı mizaçlar bir arada bulunduğunda hem güçlü hem de zorlu dinamikler yaşanabilir. Örneğin iki Safravî, güç çatışması yaşayabilir. İki Sevdavî, ortak melankolide boğulabilir. Farkındalık bu durumları yönetmeyi kolaylaştırır.' },
      { tip: 'cta', metin: 'Mizaç uyumunu detaylı incele', buton: 'Uyum Haritasını Gör', href: '/uyum' },
    ],
  },
];

export function getBlogYazisi(slug: string): BlogYazisi | undefined {
  return blogYazilari.find((y) => y.slug === slug);
}
